service: perfect-projects-access

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  iam:
    role:
      name: perfect-project-access-role
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 'iam:DeleteBucket'
  deploymentBucket:
    name: perfect-project-access


plugins:
  - serverless-deployment-bucket

resources:
  Resources:
    PerfectProjectsUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AliasAttributes:
          - preferred_username
          - email
        AutoVerifiedAttributes:
          - email
        UsernameConfiguration:
          CaseSensitive: False
        UserPoolName: perfect-projects-user-pool
    PerfectProjectUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        AccessTokenValidity: 5
        ClientName: PerfectProjects
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        GenerateSecret: True
        IdTokenValidity: 5
        PreventUserExistenceErrors: ENABLED
        RefreshTokenValidity: 30
        UserPoolId: eu-central-1_l7dofglk5
        TokenValidityUnits:
          AccessToken: minutes
          IdToken: minutes
          RefreshToken: days
        WriteAttributes:
          - preferred_username
          - email